In [1]:
import numpy as np

In [2]:
arr=np.array([34,45,45,54])

In [3]:
arr

array([34, 45, 45, 54])

In [4]:
print(arr)

[34 45 45 54]


In [5]:
np.version

<module 'numpy.version' from 'C:\\ProgramData\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [6]:
np._version_

AttributeError: module 'numpy' has no attribute '_version_'

In [7]:
np.__version__

'1.23.5'

In [8]:
type(arr)

numpy.ndarray

# Dimensions in numpy array

In [9]:
a=np.array(33)

In [19]:
b=np.array([1,2,3], ndmin=5)

In [20]:
c=np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [22]:
a.ndim

0

In [23]:
b.ndim

5

In [24]:
c.ndim

2

In [25]:
d.ndim

3

In [26]:
print("O Dimension")
print(a)
print("1 Dimension")
print(b)
print("2 Dimension")
print(c)
print("3 Dimension")
print(d)

O Dimension
33
1 Dimension
[[[[[1 2 3]]]]]
2 Dimension
[[1 2 3]
 [4 5 6]]
3 Dimension
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
