In [4]:
import numpy as np

In [5]:
arr=np.array([34,45,45,54])

In [6]:
arr

array([34, 45, 45, 54])

In [7]:
print(arr)

[34 45 45 54]


In [8]:
np.version

<module 'numpy.version' from 'C:\\ProgramData\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [9]:
np._version_

AttributeError: module 'numpy' has no attribute '_version_'

In [10]:
np.__version__

'1.23.5'

In [11]:
type(arr)

numpy.ndarray

# Dimensions in numpy array

In [12]:
a=np.array(33)

In [13]:
b=np.array([1,2,3], ndmin=5)

In [14]:
c=np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [16]:
a.ndim

0

In [17]:
b.ndim

5

In [18]:
c.ndim

2

In [19]:
d.ndim

3

In [20]:
print("O Dimension")
print(a)
print("1 Dimension")
print(b)
print("2 Dimension")
print(c)
print("3 Dimension")
print(d)

O Dimension
33
1 Dimension
[[[[[1 2 3]]]]]
2 Dimension
[[1 2 3]
 [4 5 6]]
3 Dimension
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [21]:
d[0]

array([[1, 2, 3],
       [4, 5, 6]])

# Array Indexing

In [22]:
d[0][1]

array([4, 5, 6])

In [23]:
d[0][0]

array([1, 2, 3])

In [24]:
d[0][0][0]

1

In [25]:
d[0][0][2]

3

In [27]:
d[0]+d[1]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
d[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [29]:
d[:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [30]:
d[0:0]

array([], shape=(0, 2, 3), dtype=int32)

In [31]:
d[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [32]:
z=np.array(([1,2,3,4,5,6],[7,8,9,10,11,12]))

In [33]:
z[0,-3]

4

In [34]:
z[1,-4]

9

In [35]:
y = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [38]:
y[0, 1, 0]

4

In [39]:
y[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [41]:
y[1:1]

array([], shape=(0, 2, 3), dtype=int32)

In [42]:
x=np.array([1,2,3,4,5,6, 7,8,9,10,11,12])

In [48]:
x[0:3:5]

array([1])

In [50]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) #here 0:2 means first ko and 2 indicate second array ko 2 position

[3 8]


# Data Types

In [51]:
b.dtype

dtype('int32')

In [52]:
arr.dtype

dtype('int32')

In [53]:
d.dtype

dtype('int32')

In [54]:
arr1 = np.array(['apple', 'banana', 'cherry'])

In [55]:
arr1.dtype

dtype('<U6')

In [56]:
#i - integer
#b - boolean
#u - unsigned integer
#f - float
#c - complex float
#m - timedelta
#M - datetime
#O - object
#S - string
#U - unicode string
#V - fixed chunk of memory for other type ( void )

SyntaxError: invalid syntax (3175200803.py, line 3)

In [70]:
yp=np.array([1+2j,5+3j,4+4J]) #complex datatype

In [71]:
yp

array([1.+2.j, 5.+3.j, 4.+4.j])

In [72]:
yp.dtype

dtype('complex128')

In [75]:
yp=np.array([1+2j,5+3j,4+4J], dtype="complex") #complex datatype

In [76]:
yp.dtype

dtype('complex128')

In [86]:
x=np.array([1,2,3,4,5,6, 7,8,9,10,11,12])

In [87]:
x.dtype

dtype('int32')

In [88]:
et=x.copy() #copy

In [89]:
et

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
et[1]=45

In [91]:
et

array([ 1, 45,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [92]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
new=x.view() #chnages in new has changes in x as well

In [100]:
new

array([ 1, 32,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [101]:
new[1]=32

In [102]:
new

array([ 1, 32,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
x

array([ 1, 32,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
c=np.array([[1, 2, 3], [4, 5, 6]]) #rowxcolumn

In [107]:
c.shape

(2, 3)

In [108]:
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [109]:
d.shape

(2, 2, 3)

In [110]:
d.ndim

3

In [111]:
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [112]:
e = np.array([1, 2, 3, 4], ndmin=5)

In [114]:
e.shape

(1, 1, 1, 1, 4)

In [115]:
z=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [118]:
z.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [120]:
e.reshape(2,2)

array([[1, 2],
       [3, 4]])

# Array Iteration

In [121]:
z=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [122]:
for x in z:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [123]:
d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [124]:
for i in d:
    print(i)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [126]:
len(d)

2

In [135]:
for i in d:
    x=len(i)
    for i in range(x):
            for j in range(x):
                print(d[i][j])

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [136]:
for block in d:  # Change 'i' to 'block' to avoid reuse of variable
    x = len(block)
    for i in range(x):
        for j in range(x):
            print(block[i][j])  # Use 'block' instead of 'd'


1
2
4
5
1
2
4
5


# Array Join

In [143]:
a1=np.array([1,2,3,4])

In [144]:
a2=np.array([5,6,7,8])

In [145]:
a1+a2

array([ 6,  8, 10, 12])

In [146]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
np.vstack((a1,a2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [149]:
#Split

In [150]:
np.array_split(a1,2)

[array([1, 2]), array([3, 4])]

In [151]:
c=np.array([[1, 2, 3], [4, 5, 6]])

In [152]:
newarr=np.hsplit(c, 3)

In [153]:
newarr

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [154]:
#Numpy Search

In [172]:
x1=np.array([1, 2, 43, 4, 5, 6, 7, 8])

In [173]:
x1

array([ 1,  2, 43,  4,  5,  6,  7,  8])

In [180]:
f=np.where(x1==43)

In [181]:
f

(array([2], dtype=int64),)

In [176]:
#sort
np.sort(x1)

array([ 1,  2,  4,  5,  6,  7,  8, 43])

In [177]:
x

(array([0], dtype=int64), array([0], dtype=int64))

In [178]:
x1

array([ 1,  2, 43,  4,  5,  6,  7,  8])

In [179]:
x1/5

array([0.2, 0.4, 8.6, 0.8, 1. , 1.2, 1.4, 1.6])